name: Build and Push Image

on:
    pull_request:
        branches: []
        paths-ignore:
            - 'data/**'
            - 'requirements.txt'
            - 'README.md'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build docker image
              run: |
                docker build -t train-test:1 -f ./Dockerfile .
    push:
        runs-on: ubuntu-latest
        steps:
            - 
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - 
              name: Dockerhub login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_UNAME }}
                password: ${{ secrets.DOCKERHUB_SECRET }}
                logout: true
            - 
              name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ${{ secrets.DOCKERHUB_UNAME }}/local-builds:${{ github.run_id }}
